version: '2'

services:
  integration-tester:
    build: .
    depends_on:
      - user-db
      - cart-db
  user-db:
    image: mongo:latest
    expose:
      - "27017"
  cart-db:
    image: mongo:latest
    expose:
      - "27017"
